services:
  postgres:
    image: postgres:17
    container_name: occurrence_web_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: occurrence_password
      POSTGRES_DB: occurrence_web
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - occurrence_web_postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: occurrence_web_mailpit
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
  fuseki:
    build:
      context: ./jena-fuseki-docker-6.1.0
      dockerfile: Dockerfile
      args:
        JENA_VERSION: 6.1.0

    container_name: occurrence_fuseki


    ports:
      - "127.0.0.1:3033:3030"

    volumes:
      - ./fuseki/config.ttl:/fuseki/config.ttl:ro
      - ./fuseki/secrets/passwd:/fuseki/secrets/passwd:ro
      - ./fuseki/databases:/fuseki/databases

    command:
      - "--conf"
      - "/fuseki/config.ttl"

#    networks:
#      - rdf_internal

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  occurrence_web_postgres_data:

#networks:
#  rdf_internal:
#    internal: true