services:
  postgres:
    image: postgres:17
    container_name: occurrence_web_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: occurrence_password
      POSTGRES_DB: occurrence_web
    ports:
      - "5432:5432"
    volumes:
      - occurrence_web_postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: occurrence_web_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"   

  fuseki:
    build:
      context: ./jena-fuseki-docker-6.1.0
      dockerfile: Dockerfile
      args:
        JENA_VERSION: 6.0.0
    container_name: occurrence_fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./databases:/fuseki/databases
    command:
      - "--update"
      - "--loc"
      - "databases/occurrence"
      - "/occurrence"

volumes:
  occurrence_web_postgres_data: